### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by brownad** [ruudboon/homebridge-zipatile-mqtt#1]
Are you planning to support a wide range of devices inside Zipatile?  I'm guessing the other Zipato plugin never really worked, this seems a nicer setup 👍 

Tried to pull from npm getting a few errors:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'homebridge-zipatile-mgtt' ]
2 info using npm@4.1.1
3 info using node@v6.9.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData homebridge-zipatile-mgtt
8 silly fetchNamedPackageData homebridge-zipatile-mgtt
9 silly mapToRegistry name homebridge-zipatile-mgtt
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'homebridge-zipatile-mgtt',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'homebridge-zipatile-mgtt',
12 silly mapToRegistry   name: 'homebridge-zipatile-mgtt',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/homebridge-zipatile-mgtt
14 verbose request uri https://registry.npmjs.org/homebridge-zipatile-mgtt
15 verbose request no auth needed
16 info attempt registry request try #1 at 1:54:38 PM
17 verbose request id cff427455118cb96
18 http request GET https://registry.npmjs.org/homebridge-zipatile-mgtt
19 http 404 https://registry.npmjs.org/homebridge-zipatile-mgtt
20 verbose headers { 'content-type': 'application/json',
20 verbose headers   'cache-control': 'max-age=0',
20 verbose headers   'content-length': '2',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Sat, 06 Jan 2018 13:54:39 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-lcy19238-LCY',
20 verbose headers   'x-cache': 'MISS',
20 verbose headers   'x-cache-hits': '0',
20 verbose headers   'x-timer': 'S1515246878.374951,VS0,VE1601',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 404,
21 silly get   { 'content-type': 'application/json',
21 silly get     'cache-control': 'max-age=0',
21 silly get     'content-length': '2',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Sat, 06 Jan 2018 13:54:39 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-lcy19238-LCY',
21 silly get     'x-cache': 'MISS',
21 silly get     'x-cache-hits': '0',
21 silly get     'x-timer': 'S1515246878.374951,VS0,VE1601',
21 silly get     vary: 'Accept-Encoding' } ]
22 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/homebridge-zipatile-mgtt
22 silly fetchPackageMetaData     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:304:12)
22 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:282:14)
22 silly fetchPackageMetaData     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:212:14)
22 silly fetchPackageMetaData     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:186:22)
22 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
22 silly fetchPackageMetaData     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1081:10)
22 silly fetchPackageMetaData     at emitOne (events.js:96:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
22 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1001:12)
22 silly fetchPackageMetaData  error for homebridge-zipatile-mgtt { Error: Registry returned 404 for GET on https://registry.npmjs.org/homebridge-zipatile-mgtt
22 silly fetchPackageMetaData     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:304:12)
22 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:282:14)
22 silly fetchPackageMetaData     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:212:14)
22 silly fetchPackageMetaData     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:186:22)
22 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
22 silly fetchPackageMetaData     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1081:10)
22 silly fetchPackageMetaData     at emitOne (events.js:96:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
22 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1001:12)
22 silly fetchPackageMetaData   pkgid: 'homebridge-zipatile-mgtt',
22 silly fetchPackageMetaData   statusCode: 404,
22 silly fetchPackageMetaData   code: 'E404' }
23 silly rollbackFailedOptional Starting
24 verbose stack TypeError: Cannot read property 'path' of null
24 verbose stack     at Object.Installer.rollbackFailedOptional (/usr/local/lib/node_modules/npm/lib/install.js:511:29)
24 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
24 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
24 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
24 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:337:5
24 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
24 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
24 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
24 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:294:5
24 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:16:22
25 verbose cwd /home/pi/.homebridge
26 error Linux 4.9.35-v7+
27 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-zipatile-mgtt"
28 error node v6.9.1
29 error npm  v4.1.1
30 error Cannot read property 'path' of null
31 error If you need help, you may report this error at:
31 error     <https://github.com/npm/npm/issues>
32 verbose exit [ 1, true ]

**Comment by ruudboon** [comment]
Sorry, It's still under construction. 
I'll see if I can submit a working version soon. Have one running but have to remove the hardcoded data first.

Unfortunately the options are limited. Only the local sensors are readable and controllable. [LINK](https://community.zipato.com/knowledge-base/article/internal-app-mqtt-client-documentation)

**Comment by brownad** [comment]
Cool stuff, I’ll take a look when it’s ready ping it back here when you’re happy with it 😎
